### ISSUE TITLE
URGENT debian's postrm can remove your home  

### ISSUE THREAD

**Issue by kkoralsky** [stacksync/desktop#14]
hello, 

your postrm script is critically broken

```
USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
AUTOSTART_PATH=$USER_HOME/.config/autostart

rm $AUTOSTART_PATH/stacksync.desktop
rm -rf $USER_HOME/.stacksync
```

guess what happens if you run this as root (not using sudo). please fix it asap

**Comment by adrianmo** [comment]
Hi @kkoralsky, I'm sorry to inform you that StackSync is no longer maintained. Please feel free to fork it and update it yourself.

Cheers,
-Adrián
