### ISSUE TITLE
stacksync client's sync functionality stops working after first run.

### ISSUE THREAD

**Issue by onnoval** [stacksync/desktop#9]
Hi, I have configured stacksync-server with swift. When i start stacksync clients on multiple machines, clients sync files from server correctly at first. 
When i add a file to sync folder after sometime, it is uploaded and the green checkmark icon appears on file in file browser, but other clients don't download it even after few hours. When i exit and restart these clients, they download all the files. It seems sync functionality doesn't poll for changes after first run.
Also when clients are restarted they download the file uploaded from the same machine again and renames it as "filename" + "user's conflicting copy" + "timestamp".
Please let me know how to solve this issue.

**Comment by Cotes** [comment]
Hi @onnoval,

Thank you for the detailed description of the problem. Could you tell me which versions are you using for the StackSync-server and for the clients? It would also be useful if you can provide us a log file of the desktop client to have a better understanding of the problem.

Best,
Cristian.

**Comment by onnoval** [comment]
Hi Cristian,
Thanks for replying so quickly. 
StackSync-server version is 0.6.10 and client version is v2.0-alpha2.

In the attached log files Jerry client is the one first uploading a file and Elaine client is the one who logs in afterwards and receives the files uploaded by Jerry.
But if client Jerry uploads a file while Elaine is logged in, file is uploaded with green synced icon on client Jerry but Elaine client doesn't download or discover any file uploaded.

https://drive.google.com/file/d/0B85YouGSCorrenhzdzVReEJ6Nms/view?usp=sharing

Regards,
onnoval

**Comment by Cotes** [comment]
Hi again :),

I have to analyse logs in more detail, but the problem is that you are using incompatible server/client versions. Let me take a look and I'll tell you which versions you have to use.

Best,
Cristian.

**Comment by onnoval** [comment]
Hi Cristian,

You were right about incompatible versions of server and client. It works correctly for stacksync-server version v0.5 and client version is v2.0-alpha2. Thanks.

Regards,
onnoval
